name: CI - Test and Lint

on:
  push:
    branches:
      - "**" # Run the action on every branch push
  pull_request:
    branches:
      - main # Run the action when a PR is opened against the main branch

jobs:
  test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Adjust Node.js version to match your project

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Run Linter
        run: npm run lint
